In [1]:
%matplotlib inline


What is PyTorch?
================

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [2]:
x = torch.Tensor(5, 3)
print(x)


 1.4105e+34  4.5661e-41  1.4105e+34
 4.5661e-41         nan  0.0000e+00
 4.4721e+21  1.6647e-41  6.7262e-44
 0.0000e+00  6.7262e-44  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
[torch.FloatTensor of size 5x3]



Construct a randomly initialized matrix



In [3]:
x = torch.rand(5, 3)
print(x)


 0.5540  0.8157  0.2244
 0.1766  0.0164  0.8147
 0.6820  0.2808  0.1448
 0.4515  0.3543  0.6133
 0.6295  0.9687  0.7518
[torch.FloatTensor of size 5x3]



Get its size



In [4]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports the same operations</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. Let's see addition as an example

Addition: syntax 1



In [5]:
y = torch.rand(5, 3)
print(x + y)


 0.7256  1.5305  1.1414
 1.1219  0.8911  0.8712
 1.2978  0.4655  0.7555
 1.4238  0.4084  1.1811
 1.3288  1.5247  1.2049
[torch.FloatTensor of size 5x3]



Addition: syntax 2



In [6]:
print(torch.add(x, y))


 0.7256  1.5305  1.1414
 1.1219  0.8911  0.8712
 1.2978  0.4655  0.7555
 1.4238  0.4084  1.1811
 1.3288  1.5247  1.2049
[torch.FloatTensor of size 5x3]



Addition: giving an output tensor



In [7]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 0.7256  1.5305  1.1414
 1.1219  0.8911  0.8712
 1.2978  0.4655  0.7555
 1.4238  0.4084  1.1811
 1.3288  1.5247  1.2049
[torch.FloatTensor of size 5x3]



Addition: in-place



In [8]:
# adds x to y
y.add_(x)
print(y)


 0.7256  1.5305  1.1414
 1.1219  0.8911  0.8712
 1.2978  0.4655  0.7555
 1.4238  0.4084  1.1811
 1.3288  1.5247  1.2049
[torch.FloatTensor of size 5x3]



<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard numpy-like indexing with all bells and whistles!



In [9]:
print(x[:, 1])


 0.8157
 0.0164
 0.2808
 0.3543
 0.9687
[torch.FloatTensor of size 5]



**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc are described
  `here <http://pytorch.org/docs/torch>`_

Numpy Bridge
------------

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory
locations, and changing one will change the other.

Converting torch Tensor to numpy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [10]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [11]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


See how the numpy array changed in value.



In [12]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


Converting numpy Array to torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the torch Tensor automatically



In [13]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto GPU using the ``.cuda`` function.



In [14]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

In [16]:
torch.cuda.is_available()

False

In [17]:
import torch
print("__pyTorch VERSION:", torch.__version__)


__pyTorch VERSION: 0.3.0.post4


In [18]:
print("__CUDNN VERSION:", torch.backends.cudnn.version())


__CUDNN VERSION: 7003


In [11]:
print("__Number CUDA Devices:", torch.cuda.device_count())

__Number CUDA Devices: 0


In [15]:
from subprocess import call
# call([“nvcc”, “ — version”]) does not work
! nvcc — version

print(torch.cuda.is_available())
print("__CUDNN VERSION:", torch.backends.cudnn.version())
print("__Number CUDA Devices:", torch.cuda.device_count())
print("__Devices")
call(["nvidia-smi", " — format=csv", " — query-gpu=index,name,driver_version,memory.total,memory.used,memory.free"])
print("Active CUDA Device: GPU", torch.cuda.current_device())

print ("Available devices ", torch.cuda.device_count())
print ("Current cuda device ", torch.cuda.current_device())

import torch
from torch.autograd import Variable
x=torch.Tensor(3,2)
print (type(x))
print (x)

# how variables work
x = Variable(x)
print ("x:" + str (x))
print ("requires grad:" + str(x.requires_grad))
print ("data:" + str(x.data))

/bin/sh: 1: nvcc: not found
__CUDNN VERSION: 7003
__Number CUDA Devices: 0
__Devices


AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx